services:
  - type: web
    name: idgenerator
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -c gunicorn.conf.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: "3.12"
